Make Universe Mate aware
gefarion/RTruffleMate pull request #1
Opened 2017-04-27 12:08 UTC by charig

Remove code duplication. Use instead command line arguments to decide if we are in mate or in som

2017-04-27 12:37 UTC, gefarion commented on src/som/vm/universe.py
> +        if self.vmReflectionEnabled():
Esto debería estar en el método _initialize_object_system

2017-04-27 12:43 UTC, gefarion commented on src/som/vm/universe.py
> +            elif arguments[i] == "-activateMate":
Los renombraría como: '--mate' y '--reflection' y un que --reflection implique --mate.

2017-04-27 12:45 UTC, gefarion commented on src/som/vm/universe.py
> +        self._immutable_fields_.append(
Los _inmutable_fields fields es un hint para el compilador, no estoy seguro de que funcionen si las agregas luego. De todas formas podemos agregarlas siempre, no creo que genere ningún problema.

2017-04-27 12:47 UTC, gefarion commented on src/som/vm/universe.py
> +    def vmReflectionEnabled(self):
Usamos snake case para el nombre de los métodos y campos (salvo casos particulares).

2017-04-27 12:48 UTC, gefarion requested changes
Debería funcionar bien esta solución. Solo hay que ajustar algunos detalles.

2018-05-20 20:09 UTC, closed without merging

2018-05-21 07:19 UTC, charig commented on src/som/vm/universe.py
> +            elif arguments[i] == "-activateMate":
Estos nombres era para que quede igual que trufflemate

2018-05-21 07:21 UTC, charig commented on src/som/vm/universe.py
> +        self._immutable_fields_.append(
No quise comitear este cambio perdón